name: philcst_mobilequeuing
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/img.png
    - images/abs.png

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schuyler.ttf
    - family: Trajan Pro
      fonts:
        - asset: fonts/Trajan Pro Regular.ttf

    - family: Rajdhani-SemiBold
      fonts:
        - asset: fonts/Rajdhani-SemiBold.ttf

    - family: ChakraPetch-Bold
      fonts:
        - asset: fonts/ChakraPetch-Bold.ttf